#
# Ubuntu startup configuration
# should be included *only* when ansible_distribution=='Ubuntu'

# for init.d / ubuntu <= 14.04
- block:
  - name: "[BAMBOO][UBUNTU] Installing the init.d startup"
    template:
      src: "ubuntu/etc/init.d/atlassian-bambooagent.j2"
      dest: "/etc/init.d/{{ bambooagent_service_name }}"
      owner: root
      group: root
      mode: "u+rwx,g+rx,o+rx"

  - name: "[BAMBOO][UBUNTU] Creating the log file"
    file:
      path: "/var/log/{{ bambooagent_service_name }}.log"
      state: touch
      owner: root
      mode: "u+rw"

    notify:
      - register init.d
      - restart bambooagent

  when: ansible_service_mgr != "systemd"

  rescue:
    - name: print error message
      debug:
        msg: "Error caught during the installation of the bamboo startup"
    - name: remove the startup script
      file:
        path: "/etc/init.d/{{ bambooagent_service_name }}"
        state: absent
    - name: fail the task
      fail:
        msg: An error occurred

# for systemd ubuntu>=16.04
- block:
  - name: "[BAMBOO][UBUNTU] Installing the systemd config"
    template:
      src: "ubuntu/etc/systemd/system/atlassian-bambooagent.service.j2"
      dest: "/etc/systemd/system/{{ bambooagent_service_name }}.service"
      owner: root
      group: root
      mode: 0644

  # startup script is referenced by the systemd service
  - name: "[BAMBOO][UBUNTU] Installing the startup script"
    template:
      src: "ubuntu/bamboo-startup.sh.j2"
      dest: "{{ bambooagent_install_root }}/bamboo-startup.sh"
      owner: "{{ bambooagent_user }}"
      group: "{{ bambooagent_group }}"
      mode: 0755

    notify:
      - register bambooagent service
      - restart bambooagent

  when: ansible_service_mgr == "systemd"

  rescue:
    - name: print error message
      debug:
        msg: "Error caught during the installation of the bamboo startup"
    - name: Remove startup on failure
      file:
        path: "/etc/systemd/system/{{ bambooagent_service_name }}.service"
        state: absent
    - name: Remove script on failure
      file:
        path: "{{ bambooagent_install_root }}/bamboo-startup.sh"
        state: absent
    - name: fail the task
      fail:
        msg: An error occurred
