# Installs the startup procedure for the bambooagent

#
# ensures the destination folder exists
- name: '[BAMBOO] Creating the installation folder'
  file:
    path: "{{ bambooagent_install_root }}"
    state: directory
    owner: "{{ bambooagent_user }}"
    group: "{{ bambooagent_group }}"
    mode: "u+rwx,g+rx,o+rx"
  when:
    - ansible_os_family != "Windows"

- name: '[BAMBOO] Creating the installation folder'
  win_file:
     path: "{{ bambooagent_install_root }}"
     state: directory
     owner: "{{ bambooagent_user }}"
    group: "{{ bambooagent_group }}"
  when:
    - ansible_os_family == "Windows"

#
# Copies the .jar
- name: '[BAMBOO] Copy bamboo jar into destination from existing file'
  copy:
    src: "{{ bamboo_java_jar_file }}"
    dest: "{{ bambooagent_jar_filename_full_path }}"
    owner: "{{ bambooagent_user }}"
    group: "{{ bambooagent_group }}"
    mode: "u+rw,g+r"
  when:
    - (bamboo_java_jar_file | default())
    - ansible_os_family != "Windows"

- name: '[BAMBOO][WIN] Copy bamboo jar into destination from existing file'
  win_copy:
    src: "{{ bamboo_java_jar_file }}"
    dest: "{{ bambooagent_jar_filename_full_path }}"
    owner: "{{ bambooagent_user }}"
    group: "{{ bambooagent_group }}"
    mode: "u+rw,g+r"
  when:
    - (bamboo_java_jar_file | default())
    - ansible_os_family == "Windows"

# Fetches the .jar
- name: '[BAMBOO] Fetches bamboo-agent jar into destination from server'
  get_url:
    url: "{{ bamboo_server_url }}/agentServer/agentInstaller/{{ bambooagent_jar_filename | basename }}"
    dest: "{{ bambooagent_jar_filename_full_path }}"
    owner: "{{ bambooagent_user }}"
    group: "{{ bambooagent_group }}"
    mode: "u+rw,g+r"
    validate_certs: "{{ bamboo_verify_certificates }}"
  when:
    - not (bamboo_java_jar_file | default())
    - ansible_os_family != "Windows"

- name: '[BAMBOO] Fetches bamboo-agent jar into destination from server'
  win_get_url:
    url: "{{ bamboo_server_url }}/agentServer/agentInstaller/{{ bambooagent_jar_filename | basename }}"
    dest: "{{ bambooagent_jar_filename_full_path }}"
    validate_certs: True
  when:
    - not (bamboo_java_jar_file | default())
    - ansible_os_family == "Windows"
