#
# Windows startup configuration
# should be included only when ansible_os_family=="Windows"

- block:
  - name: "[BAMBOO][WIN] stopping previous service 'bamboo-remote-agent'"
    win_service:
      name: bamboo-remote-agent
      state: stopped
    ignore_errors: True

  - name: "[BAMBOO][WIN] removing previous service 'bamboo-remote-agent'"
    win_service:
      name: bamboo-remote-agent
      state: absent

  - name: "[BAMBOO][WIN] installing the service"
    win_command: >
        java
        -Djava.io.tmpdir="{{ bambooagent_agent_root }}/tmpdir"
        -Dbamboo.home="{{ bambooagent_agent_root }}"
        -jar {{ bambooagent_jar_filename_full_path }}
        "{{ bamboo_server_url }}/agentServer/" 
        {{ bamboo_agent_security_token | ternary('-t ' + bamboo_agent_security_token,'') }}
        installntservice
    notify:
      - restart bambooagent

  - name: "[BAMBOO][WIN] fixing build folder permissions"
    win_acl:
      path: "{{ bambooagent_agent_root }}"
      user: "{{ bambooagent_user }}"
      rights: FullControl
      type: allow
      state: present

  - name: "[BAMBOO][WIN] configuring the service 'bamboo-remote-agent'"
    win_service:
      name: bamboo-remote-agent
      start_mode: auto
      username: ".\\{{ bambooagent_user }}"
      password: "{{ lookup('password', 'windows/' + inventory_hostname + '/bambooagent length=15') }}"

  rescue:
    - name: print error message
      debug:
        msg: 'Error caught during the installation of the bamboo startup'
    - name: fail the task
      win_command: "/bin/false"
