---
- name: register init.d
  command: update-rc.d {{ bambooagent_service_name }} enabled

- name: register bambooagent service
  service:
    name: "{{ bambooagent_service_name }}"
    enabled: yes
    state: reloaded

- name: restart bambooagent osx
  shell: >-
    launchctl unload -w
    /Library/LaunchDaemons/com.atlassian.{{ bambooagent_service_name }}.plist &&
    launchctl load -w
    /Library/LaunchDaemons/com.atlassian.{{ bambooagent_service_name }}.plist
  listen: "restart bambooagent"
  when: ansible_distribution == "MacOSX"

- name: restart bambooagent linux
  service:
    name: "{{ bambooagent_service_name }}"
    state: restarted
    enabled: yes
  listen: "restart bambooagent"
  when:
    - ansible_distribution == "Ubuntu"
